name: kadai4-test-automation
on:
  push:
    branches:
      master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2
      
      - name: Run kadai-test.sh
        run: bash kadai4-test.sh
